# Production Profile Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/endemonat_prod

# Production logging
logging.level.root=WARN
logging.level.com.endemonat=INFO
logging.file.name=logs/endemonat.log

# Production server configuration
server.error.include-stacktrace=never
server.error.include-message=never

# Production actuator configuration
management.endpoints.web.exposure.include=health,info