# Test Profile Configuration
spring.data.mongodb.uri=mongodb://localhost:27017/endemonat_test

# Test logging
logging.level.root=WARN
logging.level.com.endemonat=INFO

# Disable banner for tests
spring.main.banner-mode=off